- app/main.dev.js
Addresses issue where Closing wallet using Cmd-Q does not close all child-processes (particularly the mono-sgen64 process). This used to make it impossible to reopen the app without manually killing the process.
> [Patrick O] Addresses issue where Closing wallet using Cmd-Q does not

- app/main.dev.js
- app/package-lock.json
Minor refactor of logic responsible for quitting and exiting zen-node process.
The aim of this is to trigger quit and only attempt to close the node process after the `will-quit` event has been triggered.
I've tested on mac and linux and all seems to be working well. Unfortunately not tested in windows :( simply cannot get anything to run in my old windows vm.
> [Patrick O] Minor refactor

- app/components/ActivateContract/ActivateContract.js
- app/components/RunContract/RunContract.js
- app/components/SendTx/SendTx.js
- app/components/UI/Sidebar/Sidebar.js
- app/components/UI/Sidebar/_Sidebar.scss
- app/services/enforceSynced.js
- app/states/network-state.js
- simplify and clarify `netowrkState`
- create `enforceSynced` service
- wrap write operations (send, deploy contract, run contract) with `enforceSynced`. If the node isn't fully synced, a modal will popup with explanation, sync details, and option to continue with the write operation once the node has been synced.
NOTE
===
I'm aware the UI isn't great. I'm submitting this for review to make sure the logic is agreeable by everybody before we polish this.
> (SQUASH NEEDED) Protect write ops when syncing

- app/app.scss
display the scrollbar at all times, so when navigating to long pages (i.e. transactions/blockchain logs) the UI doesn't "jump" to squeeze in the scrollbar
> fix UI jump when navigating to page with scrollbar

- app/App.js
- app/app.scss
- app/main.dev.js
- app/styles/_KeyFrames.scss
- initialize window in same background color of app
- fade in UI
The app used to load a white screen, and then replaced with our UI with a dark gray/black background.
Now it fires up directly in the same background color, and the UI fades in.
> smoother UI startup

- app/index.js
- app/main.dev.js
- app/utils/crashReporter/crashReporterMainProcess.js
- app/utils/crashReporter/crashReporterRendererProcess.js
- app/utils/crashReporter/crashReporterShared.js
- package-lock.json
- package.json
- send electron crash reports to [backtrace](https://documentation.backtrace.io/product_integration_minidump_electron/)
- send uncaught renderer errors to backtrace 
I'm still waiting for an answer from their dev support about the backtrace that is send with the crash reports.
We can merge it for now, and if needed add changes later.
> Send crash reports to backtrace

- app/components/SavedContracts/SavedContracts.js
- app/components/SavedContracts/SavedContracts.scss
- app/components/SavedContracts/__tests__/SavedContract.spec.js
- app/components/TxHistory/TxHistory.js
This also addresses any inconsistencies that may have existed in the way saved contracts are sorted. In particular when saved contracts are inactive (or have no expiry date set).
Feedback welcome on the color of the disabled button. It uses the existing disabled button color variable. 
Added by @goldylucks
- disable deleting saved contract with matching asset in balances
- display modal explaining why contract can't be deleted
- improve flow annotations
- fix transactions duplicate key bug
- add tests
> Patrick: Disable delete button from saved contract list if the contract exists as an asset in the user's balances

- app/App.js
- app/ZenNode.js
- app/components/UI/Sidebar/Sidebar.js
- app/components/UI/WipeModal.js
- app/constants/versions.js
- app/services/store.js
- internals/scripts/PrintZenNodeVersion.js
- save to DB last version in which wipe occurred
- when starting zen node, automatically add `wipe` if latest required version is greater than saved version
- show modal about automatic wipe if occured
- add constants `WALLET_VERSION` and `ZEN_NODE_VERSION`
> add wipe release flag support

- DEV_README.md
- app/ZenNode.js
- change restart signal to SIGKILL (windows doesn't support SIGUSER1)
- use path.join to handle path slashes (windows uses inconsistent forward and backslashes)
- add workarounds for windows dev errors to `README_DEV`
This might fix npm on windows, if not, fixing the path(s) on the zen node package, `zen-node/index.js`, should do the trick
> fix windows mining toggle, wipe, and dev

- app/states/index.js
two reasons for doing this:
1. it will catch initializing errors of other stores
1. we got an error from a user about the `errorReportingState` not being initialized. The error came from the `PollManager` of the `networkState` store. I don't know why this happened, but maybe this will prevent future occurrences of that.
> init error store before others

- app/components/TxHistory/TxHistory.js
- app/states/__tests__/tx-history-state.spec.js
- app/states/tx-history-state.js
- use batchSize property instead of magic number 20
- show loading if is fetching transactions (changed the check [here](https://github.com/zenprotocol/zenwallet/compare/master...goldylucks:transaction-loading-fix?expand=1#diff-93fafaef324fe1c013c073527adb65bcL78), @thehogfather if we are fetching, why do we need that second check?)
We changed the batch number from 20 to 100, and the "20" was hard coded in some places.
> fix tx history loading and tests

- app/components/OnBoarding/ImportWallet/ImportWallet.js
- app/styles/_utils.scss
- test/validSeedExample.json
- show error message when each word is valid, but the seed is invalid
- refcator external link to use `ExternalLink` component
- add `validSeedExample.json` for easier future development and testing
We can merge this since it's already improves the current state of the GUI. Further changes might be needed, waiting response from the backend team.
> (ImportWallet): validate bip 39

- app/ZenNode.js
- app/config/server-address.js
Some machines have the default port taken.
This allow to set a custom port for the API.
> Custom ZEN_API port

- package.json
Before merging, please try this workaround: https://www.askvg.com/this-file-does-not-have-a-program-associated-with-it-error-message-while-running-a-game-from-game-explorer-in-windows-vista/
> attempt to fix windows run as admin

- app/components/Icons/IsValidIcon.js
- app/components/Icons/ToggleVisibilityIcon.js
- app/components/OnBoarding/ImportWallet/ImportWallet.js
- app/components/OnBoarding/SecretPhrase/SecretPhrase.js
- app/components/OnBoarding/SecretPhraseQuiz/SecretPhraseQuiz.js
- app/components/OnBoarding/SecretPhraseQuiz/SecretPhraseQuiz.scss
- app/components/UI/CopyableTableCell.js
- app/components/UI/PasteButton.js
- app/components/UI/SeedInput/SeedInput.js
- app/components/UI/SeedInput/index.js
- app/states/secret-phrase-state.js
- app/styles/_Animations.scss
- app/utils/__tests__/seedUtils.spec.js
- app/utils/domUtils.js
- app/utils/helpers.js
- app/utils/seedUtils.js
`ImportWallet`  and `SecretPhraseQuiz`
- add reset and paste buttons
- support paste with `ctrl + v`
- hide input fields+ toggle visibility option
- refactor to use `SeedInput`
---
`ImportWallet`
- improve error message
- refactor, use similar logic to `SecretPhraseQuiz`
- only update `secretPhraseState` store on completion
---
`SecretPhrase`
- add copy to clipboard button
---
MISC
- add classnames to `IsValidIcon` and `ToggleVisibilityIcon` buttons
- refactor big39 help functions and move to own file
- lint `CopyableTableCell.js`
> Improve seed logic

- app/components/ActivateContract/ActivateContract.js
- app/components/Balances/Balances.js
- app/components/RunContract/RunContract.js
- app/components/SendTx/SendTx.js
- app/components/TxHistory/SingleTxDelta.js
- app/components/UI/AmountInput/AmountInput.js
- app/components/UI/AutoSuggestAssets/AutoSuggestAssets.js
- app/components/UI/CopyableTableCell.js
- app/components/UI/Topbar/Topbar.js
- app/components/UnlockWallet/UnlockWallet.js
- app/constants/constants.js
- app/services/api-service.js
- app/states/__tests__/balances-state.spec.js
- app/states/balances-state.js
- app/states/contract-message.js
- app/states/contract-state.js
- app/states/transaction-state.js
- app/utils/helpers.js
- app/utils/zenUtils.js
fixes #72 
- cleanup a castings between numbers and strings, by doing always computations on numbers, and deriving one type from the other.
- separate numbers and their displays for assets, contracts, txs
- remove normalization from `api-service.js`, handle in stores
- move zen related helpers to `zenUtils.js`
- unify multiple injects in components
- expose names, balance, and balanceDisplay in balance store
- move some store mutations to actions
QA
===
> fix localisation number bug + refactor amount handling

- app/main.dev.js
- app/utils/prereqCheck.js
Used same mono path logic from [zen node](https://gitlab.com/zenprotocol/zenprotocol/blob/e13e135c838c2fc8c19ec70b23ab2e588a4fba3c/package/index.js#L22) package.
QA
===
> fix prereq mono check for mac

- app/components/ActiveContractSet/ActiveContractSet.js
- app/components/OnBoarding/ImportWallet/ImportWallet.js
- app/components/RunContract/RunContract.js
- app/components/SavedContracts/SavedContracts.js
- app/components/UI/PasteButton.js
- app/components/UI/ResetButton.js
- app/services/api-service.js
- app/states/index.js
- app/states/run-contract-state.js
- rename ContractMessage to RunContractState (more consistent with rest of stores + more intuitive)
- change PasteButton icon to copy
- add ResetButton UI component
- refactor import wallet with ResetButton
> Run contract clear form 

- .travis.yml
- internals/auto-release.sh
Improved travis.yml to deploy directly to npm
> NPM deployment in Travis

- app/app.scss
- app/components/AppUpdater/AppUpdateModal.js
- app/components/AppUpdater/AppUpdater.js
- app/components/AppUpdater/_AppUpdater.scss
- app/components/AppUpdater/__tests__/AppUpdater.spec.js
- app/components/AppUpdater/__tests__/appUpdate.spec.js
- app/components/AppUpdater/appUpdate.js
- app/styles/_utils.scss
- package-lock.json
- package.json
Include release text in the update prompt, to give users more insight into whether they need to update. Also bumps zen-node version.
> Show release info in update prompt, bump node version
