- app/components/RunContract/__tests__/RunContract.spec.js
- app/components/TxHistory/TxHistory.js
- app/components/TxHistory/__tests__/TxHistory.spec.js
- app/components/UI/OnScrollBottom.js
- app/services/api-service.js
- app/states/__tests__/tx-history-state.spec.js
- app/states/tx-history-state.js
- package-lock.json
- package.json
- test/defaultDbData.js
- test/mountHelpers.js
* Reactivated pagination code to allow incremental requests of transactions.
* Adds simple loading indicator in the last row of the table to show some feedback about the async action in progress.
* Adds tests and some test refactors for transactions-history-state and components
> pagination for transactions page

- app/components/Idle/autoLogoutModal.js
- app/components/Settings/Settings.scss
- app/components/Settings/newWalletUtil.js
- app/components/Settings/showSeedUtil.js
- app/hocs/__tests__/withCountdown.spec.js
- app/hocs/withCountdown.js
- create hocs library ([higher order components](https://reactjs.org/docs/higher-order-components.html))
- create withCountdown HOC (for modals: show seed, new wallet, autologout)
- update logic of Settings > New wallet
> New wallet ux

- app/main.dev.js
- package-lock.json
- package.json
> enable dev tools on production

- app/components/OnBoarding/SetPassword/SetPassword.js
- app/constants/constants.js
- app/states/secret-phrase-state.js
- in case of error, show error to user
- show "importing ..." in button when in progress
- move to next page only after successful import
> fix import wallet flow after setting password

- app/components/ActivateContract/ActivateContract.js
- app/states/contract-state.js
- reset form on componentWillUnmount
- improve flow type for status
- refactor error sdk link with ExternalLink component
- fix spacing in error sdk link
> Deploy contract: fix reappearing error msg on routing

- app/states/network-state.js
- app/utils/PollManager.js
continue polling after an error
> fix polling after toggling minner

- app/components/OnBoarding/SetPassword/SetPassword.js
- app/states/network-state.js
- prints out unexpected undefined values
- fallback to initial state if response is undefined
- fix typo in importing wallet: importing -> Importing (capital "i")
> Protect network response

- README.md
- app/ZenNode.js
- app/__tests__/ZenNode.spec.js
- app/components/OnBoarding/ErrorReportingOptIn/ErrorReportingOptIn.js
- app/components/OnBoarding/Layout/Layout.js
- app/components/Settings/Settings.js
- app/components/Settings/logoutUtil.js
- app/components/Settings/switchChain.js
- app/components/UI/NonMainNetBottomBar.js
- app/components/UI/Sidebar/Sidebar.js
- app/components/UI/Sidebar/_Sidebar.scss
- app/components/UnlockWallet/UnlockWallet.js
- app/config/server-address.js
- app/constants/constants.js
- app/package.json
- app/services/confirmPasswordModal.js
- app/services/enforceSynced.js
- app/states/network-state.js
- bin/zen-wallet.js
- package-lock.json
- package.json
- test/mockDb.js
- add bottom bar warning if not running on mainnet
- add info text in require password modal if not running on mainnet
- support local, test and mainnet for zen node and zen-wallet bin
- add button in settings to switch between test/main net
- README: link to DEV_README for dev
- refacor settings logout logic to own file
- fix sidebar network status for local chain
- fix zennode tests
- fix mock db in tests
> Support test, main and local chain/net

- app/components/Loading/LoadingUtil.js
- app/components/OnBoarding/Layout/Layout.js
- app/components/OnBoarding/Layout/Layout.scss
- app/components/UI/Topbar/_Topbar.scss
- app/states/network-state.js
- app/styles/_Variables.scss
- fix header height (was cut in the middle before)
- fix "unknown chain" by fetching network info on load
- fix overlapping buttons and non mainnet bottom warning bar
> Fix onboarding UI

- app/components/ActivateContract/ActivateContract.js
- app/config/server-address.js
- app/constants/constants.js
- app/states/__tests__/balances-state.spec.js
- app/states/balances-state.js
- app/styles/_utils.scss
- app/utils/helpers.js
- disallow use of 00, Zp, zP, ZP as contract name
- add zen contract name (ZP) to constants
- refactor existing uses of hardcoded ZP strings to use constant
- remove server address chain log
> protect contract name (00, ZP)

- app/components/Icons/ToggleVisibilityIcon.js
- app/components/OnBoarding/SecretPhrase/SecretPhrase.js
- app/components/OnBoarding/SecretPhraseQuiz/SecretPhraseQuiz.js
- app/components/UI/SeedInput/SeedInput.js
- `SecretPhrase` - remove copy to clipboard
- reverse eye icon logic (with/out slash)
Better not to squash the commits on this PR, they are not related to each other.
> Seed logic 2

- app/ZenNode.js
- app/components/AppUpdater/appUpdate.js
- app/main.dev.js
- app/utils/platformUtils.js
- app/utils/prereqCheck.js
- package-lock.json
- package.json
- validate above prerequisites
- show relevant error message to user if needed
- add platform utils
- refactor app updater with platform utils
QA
===
I don't know how to QA Z3 not working. maybe @somdoron have an idea.
(patch version doesn't matter)
> check mono, z3, and 64 bit OS

- app/utils/prereqCheck.js
z3 was broken, platform checking methods weren't invoked, forgot to add parenthesis
> fix prereq checks

- app/utils/__tests__/zenUtils.spec.js
- app/utils/helpers.js
- app/utils/zenUtils.js
- package-lock.json
- package.json
- add tests
- use decimal.js for zen math calculations
> fix zen balance display

- .eslintrc.js
- app/components/Receive/Receive.js
- app/components/UI/Copy.js
- app/components/UI/Toggle.js
- app/services/api-service.js
- app/states/public-address-state.js
- app/styles/_Forms.scss
- package-lock.json
- package.json
- add Copy HOC
- add Togle HOC
- add error checking for getPublicAddress
- add cursor to labels with for
- eslint remove jsx-a11y/no-noninteractive-element-interactions
> feat(Receive): add PkHash support

- app/components/UI/Sidebar/Sidebar.js
- app/states/network-state.js
better have components handle only the rendering :)
> move hashrate logic to store

- app/components/Receive/Receive.js
- app/components/UI/Copy.js
- app/components/UI/Toggle.js
- change toggle checkbox to arrow
- align center the toggle
- highlight input text on copy
> UI/UX touchup fo receive + pkHash

- app/components/UI/Topbar/Topbar.js
- use flow instead of proptypes
- improve classname handling
- cleanup unused code
> (TopBar): remove "Total", refactor

- app/components/Idle/autoLogoutModal.js
was caused by sweetalert, apparently it doesn't handle well HOCs
> fix(autologout): fix error thrown when autologging out

- app/components/OnBoarding/SecretPhrase/SecretPhrase.js
- app/components/RunContract/RunContract.js
- app/services/api-service.js
- app/states/run-contract-state.js
- on body erorr: show body error and disable form
- use flow instead of prop types
- fix non spaced text
- cleanup unused code and lint
- `api-service` update types
- move run contract payload logic to store
> (Run Contract) add returnAddress + fix empty body bug

- .travis.yml
- DEV_README.md
- app/onBoardingPages/ErrorReportingOptIn/ErrorReportingOptIn.js
- app/onBoardingPages/ImportOrCreateWallet/ImportOrCreateWallet.js
- app/onBoardingPages/ImportWallet/ImportWallet.js
- app/onBoardingPages/SecretPhrase/SecretPhrase.js
- app/onBoardingPages/SecretPhraseQuiz/SecretPhraseQuiz.js
- app/onBoardingPages/SetPassword/SetPassword.js
- app/onBoardingPages/TermsOfService/TermsOfService.js
- app/onBoardingPages/WelcomeMessages/WelcomeMessages.js
- app/pages/SendTx/SendTx.js
- package.json
> Fix on BigRefractor

- app/pages/Settings/Settings.js
- app/services/api-service.js
> Fix Import a new wallet

- app/components/ProtectedButton/ProtectedButton.js
- app/components/ProtectedButton/enforceSyncedModal.js
- app/components/ProtectedButton/index.js
- app/pages/DeployContract/DeployContract.js
- app/pages/RunContract/RunContract.js
- app/pages/SendTx/SendTx.js
- app/services/confirmPasswordModal.js
- fix redundant api call to check password when user doesn't input password
> refactor write operations to use `ProtectedButton` component

- app/ZenNode.js
fixes [this issue](https://trello.com/c/MAa67ZAR/394-miner-icon-on-in-mainnet)
> fix mining on mainnet

- app/pages/TxHistory/SingleTxDelta.js
- app/stores/portfolioStore.js
Added subtype name as @somdoron did in web wallet [PR(10)](https://github.com/zenprotocol/webwallet/pull/10/)
> added suptype name

- app/components/CopyableTableCell.js
- app/pages/TxHistory/SingleTxDelta.js
Fixed Linkin Tx History for testnet
> Fixed Link for testnet

- app/components/Sidebar/SidebarMenu.js
- app/stores/secretPhraseStore.js
> removed faucet

- app/components/BoxLabel/BoxLabel.js
- app/components/BoxLabel/_BoxLabel.scss
- app/pages/CGP/CGP.js
- app/pages/CGP/_CGP.scss
- app/styles/_Forms.scss
- app/styles/_Variables.scss
fixed top 5 boxes and CGP Form
> CGP CSS Touchups

- app/ZenNode.js
- app/__tests__/ZenNode.spec.js
- app/pages/Settings/switchChain.js
- app/services/db.js
- app/stores/blockchainLogsStore.js
- app/stores/index.js
- limitless logs instead of 200
- persist blockchain logs when switching chains
- optimize log communication between main and renderer process
> Limitless logs

- app/pages/ActiveContracts/ActiveContracts.js
- app/stores/blockchainLogsStore.js
- app/stores/runContractStore.js
- app/styles/_Table.scss
- `runContractStore` - refactor run/save contract
- `_Table.scss` - add `isDisabled` helper class
> add "save contract locally" to active contracts
